"use client";

import "leaflet/dist/leaflet.css";
import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";

import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ResponsiveGridLayout, useContainerWidth, type ResponsiveLayouts } from "react-grid-layout";
import {
  Area,
  Bar,
  BarChart,
  CartesianGrid,
  ComposedChart,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import type { FeatureCollection } from "geojson";
import type { LatLngBounds, Map as LeafletMap, Path as LeafletPath } from "leaflet";
import { DownloadImageButton, Icon, IconButton, Modal, type IconName } from "@/components/ChartTools";
import { GRID, MODEL_LABEL, SERIES, SURFACE, axisTick, tooltipValue } from "@/lib/chart-theme";
import {
  INDICATORS,
  MONTHS,
  UNASSIGNED_DIVISION,
  addRecord,
  canonicalGeoName,
  decodeDataset,
  emptyTotals,
  formatMeasure,
  groupTotals,
  isIndicator,
  measureLabel,
  measureValue,
  testPositivityRate,
  totalsOf,
  upazilaMatchKey,
  type MeasureKey,
  type MisDataset,
  type MisRecord,
  type Totals,
} from "@/lib/malaria-metrics";

/* -------------------------------- Config -------------------------------- */

type Leaflet = typeof import("leaflet");
type GeoLevel = "division" | "district" | "upazila";
type WidgetId = "kpis" | "trend" | "forecast" | "map" | "species" | "areas";
type GeoRecord = MisRecord & { divisionKey: string; districtKey: string; upazilaKey: string };
interface GeoPick {
  key: string;
  label: string;
}
interface GeoSelection {
  division: GeoPick | null;
  district: GeoPick | null;
  upazila: GeoPick | null;
}
interface GeoOptions {
  divisions: GeoPick[];
  districts: Map<string, GeoPick[]>;
  upazilas: Map<string, GeoPick[]>;
}
interface AreaStat {
  key: string;
  label: string;
  totals: Totals;
  value: number | null;
}

/** Local GeoJSON in /public/geo, generated by `npm run geo:prepare` (geoBoundaries BGD ADM1–3). */
const GEO_LEVELS: Record<GeoLevel, { url: string; nameProp: string; parentProp: string | null; label: string }> = {
  division: { url: "/geo/bd-divisions.geojson", nameProp: "ADM1_EN", parentProp: null, label: "Divisions" },
  district: { url: "/geo/bd-districts.geojson", nameProp: "ADM2_EN", parentProp: "ADM1_EN", label: "Districts" },
  upazila: { url: "/geo/bd-upazilas.geojson", nameProp: "ADM3_EN", parentProp: "ADM2_EN", label: "Upazilas" },
};

const MAP_METRICS: MeasureKey[] = ["cases", "deaths", "tests", "tpr", "pfShare", "api", "aber"];
const KPI_METRICS: { key: MeasureKey; icon: IconName }[] = [
  { key: "cases", icon: "cases" },
  { key: "deaths", icon: "deaths" },
  { key: "tests", icon: "tests" },
  { key: "tpr", icon: "percent" },
  { key: "pfShare", icon: "microscope" },
  { key: "api", icon: "activity" },
  { key: "aber", icon: "droplet" },
];

// Quantile scale for non-case metrics: light yellow → red.
const PALETTE = ["#fef9c3", "#fde68a", "#fbbf24", "#f97316", "#dc2626"];
/**
 * Case map classes depend on the map level, so red always means "high for this kind of area":
 * divisions red above 1,000 cases, districts above 500, upazilas above 200.
 * Classes: 0 (ash) · 1–9 (pale, next to the first warm step) · three warm steps · red.
 */
const CASE_PALETTE = ["#b9b9b6", "#fde9a8", "#fbbf5a", "#f5893a", "#e4502f", "#b91c1c"];
const CASE_BREAKS: Record<GeoLevel, number[]> = {
  division: [0, 9, 250, 500, 1000],
  district: [0, 9, 100, 250, 500],
  upazila: [0, 9, 50, 100, 200],
};
const NO_DATA = "#eceae4";
const DEATH_RED = "#c81e1e";
const LAYOUT_KEY = "malaria-mis:bi-layouts:v2";
const LEGEND_FMT = new Intl.NumberFormat("en-US", { maximumSignificantDigits: 3 });
const COUNT_FMT = new Intl.NumberFormat("en-US");
// Rates from fewer tests than this are ranked last in the area table (e.g. 3 tests → TPR 100%).
const MIN_TESTS_FOR_RANKING = 50;

const DEFAULT_LAYOUTS: ResponsiveLayouts = {
  lg: [
    { i: "kpis", x: 0, y: 0, w: 12, h: 4, minH: 3 },
    { i: "trend", x: 0, y: 4, w: 7, h: 8, minW: 4, minH: 6 },
    { i: "map", x: 7, y: 4, w: 5, h: 15, minW: 3, minH: 8 },
    { i: "forecast", x: 0, y: 12, w: 7, h: 11, minW: 4, minH: 8 },
    { i: "areas", x: 7, y: 19, w: 5, h: 11, minW: 3, minH: 5 },
    { i: "species", x: 0, y: 23, w: 7, h: 7, minW: 4, minH: 5 },
  ],
};

function readStoredLayouts(): ResponsiveLayouts {
  if (typeof window === "undefined") return DEFAULT_LAYOUTS;
  try {
    const parsed: unknown = JSON.parse(window.localStorage.getItem(LAYOUT_KEY) ?? "null");
    if (parsed && typeof parsed === "object" && Object.values(parsed).every(Array.isArray)) {
      return parsed as ResponsiveLayouts;
    }
  } catch {
    /* storage unavailable or corrupt */
  }
  return DEFAULT_LAYOUTS;
}

/* ------------------------------- Helpers -------------------------------- */

const round2 = (v: number | null) => (v === null ? null : Math.round(v * 100) / 100);
const periodOf = (r: MisRecord) => `${r.year}-${String(r.month).padStart(2, "0")}`;

function quantileBreaks(values: number[], classes = PALETTE.length): number[] {
  const unique = [...new Set(values)].sort((a, b) => a - b);
  if (unique.length < 2) return [];
  const n = Math.min(classes, unique.length);
  const breaks: number[] = [];
  for (let i = 1; i < n; i++) breaks.push(unique[Math.floor((i * unique.length) / n) - 1]);
  return [...new Set(breaks)];
}

/** Spread the classes in use across the whole palette, light → dark. */
const paletteAt = (index: number, breakCount: number) =>
  PALETTE[breakCount ? Math.round((index * (PALETTE.length - 1)) / breakCount) : 0];

const classColor = (index: number, breaks: number[], metric: MeasureKey) =>
  metric === "cases" ? CASE_PALETTE[index] : paletteAt(index, breaks.length);

function mapColor(value: number | null, breaks: number[], metric: MeasureKey): string {
  if (value === null) return NO_DATA;
  return classColor(breaks.filter((b) => value > b).length, breaks, metric);
}

const isReliable = (s: AreaStat, metric: MeasureKey) => !isIndicator(metric) || s.totals.tests >= MIN_TESTS_FOR_RANKING;

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] ?? c);
}

const geoCache = new Map<string, Promise<FeatureCollection>>();

function loadGeoJson(url: string): Promise<FeatureCollection> {
  let pending = geoCache.get(url);
  if (!pending) {
    pending = fetch(url).then(async (res) => {
      if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
      return (await res.json()) as FeatureCollection;
    });
    pending.catch(() => geoCache.delete(url));
    geoCache.set(url, pending);
  }
  return pending;
}

/* ------------------------------ UI pieces -------------------------------- */

function Widget({
  title,
  downloadName,
  onExpand,
  clickToExpand,
  children,
}: {
  title: string;
  downloadName: string;
  onExpand: () => void;
  clickToExpand?: boolean;
  children: ReactNode;
}) {
  const bodyRef = useRef<HTMLDivElement>(null);
  return (
    <div className="flex h-full flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <div className="widget-handle flex cursor-move items-center justify-between gap-2 border-b border-slate-100 px-3 py-1.5">
        <h3 className="truncate text-sm font-semibold text-slate-700">⠿ {title}</h3>
        <div className="widget-no-drag flex cursor-default items-center gap-1.5">
          <DownloadImageButton target={bodyRef} filename={downloadName} />
          <IconButton icon="expand" label="Open larger (with drill-down)" onClick={onExpand} />
        </div>
      </div>
      <div
        ref={bodyRef}
        className={`min-h-0 flex-1 bg-white p-3 ${clickToExpand ? "cursor-zoom-in" : ""}`}
        onClick={clickToExpand ? onExpand : undefined}
        title={clickToExpand ? "Click to open larger" : undefined}
      >
        {children}
      </div>
    </div>
  );
}

function MapLegend({ breaks, metric, level }: { breaks: number[]; metric: MeasureKey; level: GeoLevel }) {
  const counts = !isIndicator(metric) && breaks.every(Number.isInteger);
  const f = (v: number) => (counts ? COUNT_FMT.format(v) : LEGEND_FMT.format(v));
  const items = Array.from({ length: breaks.length ? breaks.length + 1 : 0 }, (_, i) => {
    const lo = i === 0 ? null : breaks[i - 1];
    const hi = i < breaks.length ? breaks[i] : null;
    const text = counts
      ? lo === null
        ? hi === 0 ? "0" : `≤ ${f(hi ?? 0)}`
        : hi === null
          ? `> ${f(lo)}`
          : lo + 1 === hi ? f(hi) : `${f(lo + 1)} – ${f(hi)}`
      : lo === null
        ? `≤ ${f(hi ?? 0)}`
        : hi === null
          ? `> ${f(lo)}`
          : `${f(lo)} – ${f(hi)}`;
    return { color: classColor(i, breaks, metric), text };
  });
  return (
    <div className="pointer-events-none absolute bottom-2 left-2 z-[1000] rounded bg-white/90 p-2 text-[11px] shadow">
      <div className="mb-1 font-semibold text-slate-700">
        {measureLabel(metric)}
        {metric === "cases" ? <span className="font-normal text-slate-500"> · {GEO_LEVELS[level].label.toLowerCase()}</span> : null}
      </div>
      {[...items, { color: NO_DATA, text: "No reports" }].map((item, i) => (
        <div key={i} className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-sm border border-slate-300" style={{ background: item.color }} />
          {item.text}
        </div>
      ))}
    </div>
  );
}

/** Division → District → Upazila drill controls (map and table clicks do the same). */
function GeoPicker({ options, geo, onChange }: { options: GeoOptions; geo: GeoSelection; onChange: (next: GeoSelection) => void }) {
  const districts = geo.division ? (options.districts.get(geo.division.key) ?? []) : [];
  const upazilas = geo.district ? (options.upazilas.get(geo.district.key) ?? []) : [];
  const select = "max-w-36 rounded border border-slate-300 bg-white px-1.5 py-1 text-xs disabled:opacity-50";
  return (
    <div className="flex flex-wrap items-center gap-1.5" data-no-export="true">
      <span className="flex items-center gap-1 text-xs text-slate-500"><Icon name="layers" className="h-3.5 w-3.5" /> Go deeper</span>
      <select aria-label="Division" value={geo.division?.key ?? ""} className={select}
        onChange={(e) => onChange({ division: options.divisions.find((d) => d.key === e.target.value) ?? null, district: null, upazila: null })}>
        <option value="">All divisions</option>
        {options.divisions.map((d) => <option key={d.key} value={d.key}>{d.label}</option>)}
      </select>
      <select aria-label="District" disabled={!geo.division} value={geo.district?.key ?? ""} className={select}
        onChange={(e) => onChange({ division: geo.division, district: districts.find((d) => d.key === e.target.value) ?? null, upazila: null })}>
        <option value="">{geo.division ? "All districts" : "District…"}</option>
        {districts.map((d) => <option key={d.key} value={d.key}>{d.label}</option>)}
      </select>
      <select aria-label="Upazila" disabled={!geo.district} value={geo.upazila?.key ?? ""} className={select}
        onChange={(e) => onChange({ ...geo, upazila: upazilas.find((u) => u.key === e.target.value) ?? null })}>
        <option value="">{geo.district ? "All upazilas" : "Upazila…"}</option>
        {upazilas.map((u) => <option key={u.key} value={u.key}>{u.label}</option>)}
      </select>
      {geo.division && (
        <button type="button" title="Go up one level" className="rounded border border-slate-300 px-1.5 py-1 text-xs hover:bg-slate-50"
          onClick={() => onChange(geo.upazila ? { ...geo, upazila: null } : geo.district ? { division: geo.division, district: null, upazila: null } : { division: null, district: null, upazila: null })}>
          ↑ Up
        </button>
      )}
    </div>
  );
}

/* ----------------------------- Choropleth map ---------------------------- */

function ChoroplethMap({
  level,
  parentKey,
  selectedKey,
  stats,
  breaks,
  metric,
  onSelect,
}: {
  level: GeoLevel;
  parentKey: string | null;
  selectedKey: string | null;
  stats: Map<string, AreaStat>;
  breaks: number[];
  metric: MeasureKey;
  onSelect: (name: string) => void;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<LeafletMap | null>(null);
  const leafletRef = useRef<Leaflet | null>(null);
  const fittedRef = useRef("");
  const boundsRef = useRef<LatLngBounds | null>(null);
  const interactedRef = useRef(false);
  const onSelectRef = useRef(onSelect);
  const [ready, setReady] = useState(false);
  const [geo, setGeo] = useState<{ level: GeoLevel; data: FeatureCollection } | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    onSelectRef.current = onSelect;
  }, [onSelect]);

  // Init Leaflet client-side only.
  useEffect(() => {
    let disposed = false;
    let observer: ResizeObserver | undefined;
    let detach: (() => void) | undefined;
    import("leaflet")
      .then((mod) => {
        const el = containerRef.current;
        if (disposed || !el) return;
        const L = (mod as unknown as { default?: Leaflet }).default ?? (mod as Leaflet);
        leafletRef.current = L;
        // Wheel zoom only after a click, so page scrolling over the widget doesn't zoom the map.
        const map = L.map(el, { center: [23.7, 90.35], zoom: 7, zoomSnap: 0.25, scrollWheelZoom: false });
        L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
          maxZoom: 18,
          opacity: 0.35,
          crossOrigin: "anonymous",
          attribution: "&copy; OpenStreetMap contributors · Boundaries: geoBoundaries",
        }).addTo(map);
        map.on("click", () => map.scrollWheelZoom.enable());
        map.on("mouseout", () => map.scrollWheelZoom.disable());
        mapRef.current = map;

        const markInteracted = () => {
          interactedRef.current = true;
        };
        el.addEventListener("pointerdown", markInteracted);
        detach = () => el.removeEventListener("pointerdown", markInteracted);

        // Grid widgets resize after mount; keep the current area framed until the user pans/zooms.
        observer = new ResizeObserver(() => {
          map.invalidateSize();
          if (boundsRef.current && !interactedRef.current) map.fitBounds(boundsRef.current, { padding: [12, 12] });
        });
        observer.observe(el);
        setReady(true);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : String(err)));
    return () => {
      disposed = true;
      detach?.();
      observer?.disconnect();
      mapRef.current?.remove();
      mapRef.current = null;
      fittedRef.current = "";
    };
  }, []);

  // Load boundaries for the current drill level.
  useEffect(() => {
    let cancelled = false;
    loadGeoJson(GEO_LEVELS[level].url)
      .then((data) => {
        if (cancelled) return;
        setGeo({ level, data });
        setError(null);
      })
      .catch((err: unknown) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      });
    return () => {
      cancelled = true;
    };
  }, [level]);

  // Draw choropleth.
  useEffect(() => {
    const map = mapRef.current;
    const L = leafletRef.current;
    if (!ready || !map || !L || !geo || geo.level !== level) return;

    const cfg = GEO_LEVELS[level];
    const nameOf = (props: Record<string, unknown> | null | undefined) => String(props?.[cfg.nameProp] ?? "");
    const keyOf = (name: string) => (level === "upazila" ? upazilaMatchKey(name) : canonicalGeoName(name));
    const features = geo.data.features.filter(
      (f) => !cfg.parentProp || !parentKey || canonicalGeoName(String(f.properties?.[cfg.parentProp] ?? "")) === parentKey,
    );

    let selectedLayer: LeafletPath | null = null;
    const layer = L.geoJSON({ type: "FeatureCollection", features } as FeatureCollection, {
      style: (feature) => {
        const key = keyOf(nameOf(feature?.properties));
        const selected = selectedKey !== null && key === selectedKey;
        return {
          color: selected ? "#0f172a" : "#57534e",
          weight: selected ? 3 : 0.8,
          fillOpacity: selectedKey !== null && !selected ? 0.55 : 0.88,
          fillColor: mapColor(stats.get(key)?.value ?? null, breaks, metric),
        };
      },
      onEachFeature: (feature, lyr) => {
        const name = nameOf(feature.properties);
        const stat = stats.get(keyOf(name));
        if (selectedKey !== null && keyOf(name) === selectedKey) selectedLayer = lyr as LeafletPath;
        lyr.bindTooltip(
          `<strong>${escapeHtml(name)}</strong><br/>` +
            `${escapeHtml(measureLabel(metric))}: ${escapeHtml(formatMeasure(metric, stat?.value ?? null))}<br/>` +
            `Cases: ${escapeHtml(formatMeasure("cases", stat?.totals.cases ?? null))} · ` +
            `Deaths: ${escapeHtml(formatMeasure("deaths", stat?.totals.deaths ?? null))} · ` +
            `Tested: ${escapeHtml(formatMeasure("tests", stat?.totals.tests ?? null))}`,
          { sticky: true },
        );
        lyr.on({
          click: () => onSelectRef.current(name),
          mouseover: (e) => (e.target as LeafletPath).setStyle({ weight: 2.5, color: "#0f172a" }),
          mouseout: (e) => layer.resetStyle(e.target as LeafletPath),
        });
      },
    }).addTo(map);

    const fitKey = `${level}|${parentKey ?? ""}|${selectedKey ?? ""}`;
    if (features.length && fittedRef.current !== fitKey) {
      const target = selectedLayer as (LeafletPath & { getBounds?: () => LatLngBounds }) | null;
      boundsRef.current = target?.getBounds ? target.getBounds() : layer.getBounds();
      interactedRef.current = false;
      map.invalidateSize();
      map.fitBounds(boundsRef.current, { padding: [12, 12], maxZoom: 11 });
      fittedRef.current = fitKey;
    }
    return () => {
      layer.remove();
    };
  }, [ready, geo, level, parentKey, selectedKey, stats, breaks, metric]);

  return (
    <div className="relative isolate h-full w-full overflow-hidden rounded-md">
      <div ref={containerRef} className="h-full w-full bg-slate-50" />
      <MapLegend breaks={breaks} metric={metric} level={level} />
      {error && (
        <div className="absolute inset-x-2 top-2 z-[1000] rounded bg-amber-50 p-2 text-xs text-amber-800 shadow">
          Map boundaries unavailable ({error}). Run <code>npm run geo:prepare</code>.
        </div>
      )}
    </div>
  );
}

/* ----------------------- Cases · deaths · tests + forecast ---------------------- */

interface ForecastPoint { year: number; month: number; yhat: number; lo80: number; hi80: number }
interface ForecastApi {
  selected?: { area_name: string };
  cases?: { run: { model: string; accuracy_pct: number | null; accuracy_3m_pct: number | null } | null; forecast: ForecastPoint[] };
  deaths?: { forecast: ForecastPoint[] };
}

function ForecastPanel({
  area,
  records,
  year,
  latestYear,
  upazila,
}: {
  area: { level: string; key: string; label: string };
  records: GeoRecord[];
  year: number | "all";
  latestYear: number | null;
  upazila: string | null;
}) {
  // Forecasts exist down to district level and continue from the latest data month.
  const showForecast = !upazila && (year === "all" || year === latestYear);
  const [result, setResult] = useState<{ id: string; data: ForecastApi | null } | null>(null);
  const id = `${area.level}|${area.key}`;

  useEffect(() => {
    let cancelled = false;
    const [level, key] = id.split("|");
    fetch(`/api/insights/forecast?level=${encodeURIComponent(level)}&key=${encodeURIComponent(key)}`)
      .then(async (res) => {
        const json = (await res.json()) as ForecastApi;
        if (!cancelled) setResult({ id, data: res.ok ? json : null });
      })
      .catch(() => !cancelled && setResult({ id, data: null }));
    return () => {
      cancelled = true;
    };
  }, [id]);

  const data = result?.id === id ? result.data : null;
  const rows = useMemo(() => {
    const inPeriod = year === "all" ? records : records.filter((r) => r.year === year);
    const monthly = [...groupTotals(inPeriod, periodOf)].sort((a, b) => a[0].localeCompare(b[0])).slice(year === "all" ? -36 : 0);
    const out: Record<string, string | number | number[] | null>[] = monthly.map(([period, t]) => ({
      period,
      cases: t.cases,
      deaths: t.deaths,
      tests: t.tests,
      tpr: round2(testPositivityRate(t.cases, t.tests)),
    }));
    const last = out[out.length - 1];
    const cases = showForecast ? (data?.cases?.forecast ?? []) : [];
    const deaths = showForecast ? (data?.deaths?.forecast ?? []) : [];
    if (last && cases.length) {
      last.fcCases = last.cases;
      last.band80 = [Number(last.cases), Number(last.cases)];
      last.fcDeaths = last.deaths;
    }
    const lastPeriod = String(last?.period ?? "");
    cases.forEach((f, i) => {
      const period = `${f.year}-${String(f.month).padStart(2, "0")}`;
      if (period <= lastPeriod) return;
      out.push({ period, fcCases: Math.round(f.yhat), band80: [Math.round(f.lo80), Math.round(f.hi80)], fcDeaths: deaths[i] ? Math.round(deaths[i].yhat * 10) / 10 : null });
    });
    return out;
  }, [records, data, year, showForecast]);

  const run = data?.cases?.run;
  const chartMargin = { top: 4, right: 8, bottom: 0, left: 0 };
  const panelClass = "min-h-0 flex-1";

  return (
    <div className="flex h-full flex-col gap-1">
      <p className="text-[11px] text-slate-500">
        {upazila
          ? <>Actual data for <b>{upazila}</b>. Forecasts are made for Bangladesh, divisions and districts — select “All upazilas” to see the district forecast.</>
          : !showForecast
            ? <>Actual data for <b>{year}</b>. Choose the latest year or “All loaded” to see the 18-month forecast.</>
            : run
          ? <>Forecast for <b>{data?.selected?.area_name}</b> · {MODEL_LABEL[run.model] ?? run.model} · back-tested accuracy <b>{run.accuracy_pct ?? "—"}%</b> (1 month) / <b>{run.accuracy_3m_pct ?? "—"}%</b> (3 months)</>
          : result?.id === id
            ? <>No forecast for {area.label} (too few recent cases) — actual data only.</>
            : <>Loading forecast…</>}
      </p>
      <div className={panelClass}>
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={rows} syncId="bi-forecast" margin={chartMargin}>
            <CartesianGrid vertical={false} stroke={GRID} />
            <XAxis dataKey="period" tick={axisTick} minTickGap={32} hide />
            <YAxis tick={axisTick} width={48} />
            <Tooltip formatter={tooltipValue} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Area dataKey="band80" name="Forecast 80% range" stroke="none" fill={SERIES[1]} fillOpacity={0.2} isAnimationActive={false} />
            <Line dataKey="cases" name="Confirmed cases" stroke={SERIES[0]} strokeWidth={2} dot={false} isAnimationActive={false} />
            <Line dataKey="fcCases" name="Case forecast" stroke={SERIES[1]} strokeWidth={2} strokeDasharray="5 4" dot={false} isAnimationActive={false} />
          </ComposedChart>
        </ResponsiveContainer>
      </div>
      <div className={panelClass}>
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={rows} syncId="bi-forecast" margin={chartMargin}>
            <CartesianGrid vertical={false} stroke={GRID} />
            <XAxis dataKey="period" tick={axisTick} minTickGap={32} hide />
            <YAxis tick={axisTick} width={48} allowDecimals={false} />
            <Tooltip formatter={tooltipValue} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Bar dataKey="deaths" name="Deaths" fill={DEATH_RED} radius={[3, 3, 0, 0]} isAnimationActive={false} />
            <Line dataKey="fcDeaths" name="Expected deaths" stroke={DEATH_RED} strokeWidth={2} strokeDasharray="5 4" dot={false} isAnimationActive={false} />
          </ComposedChart>
        </ResponsiveContainer>
      </div>
      <div className={panelClass}>
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={rows} syncId="bi-forecast" margin={chartMargin}>
            <CartesianGrid vertical={false} stroke={GRID} />
            <XAxis dataKey="period" tick={axisTick} minTickGap={32} />
            <YAxis tick={axisTick} width={48} />
            <Tooltip formatter={tooltipValue} />
            <Legend wrapperStyle={{ fontSize: 11 }} />
            <Line dataKey="tests" name="People tested" stroke={SERIES[2]} strokeWidth={2} dot={false} isAnimationActive={false} />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

/* ------------------------------- Component ------------------------------- */

export default function BiTab({ dataset }: { dataset: MisDataset }) {
  const records = useMemo<GeoRecord[]>(
    () =>
      decodeDataset(dataset).map((r) => ({
        ...r,
        divisionKey: canonicalGeoName(r.divisionName),
        districtKey: canonicalGeoName(r.districtName),
        upazilaKey: upazilaMatchKey(r.upazilaName),
      })),
    [dataset],
  );
  const years = useMemo(() => [...new Set(records.map((r) => r.year))].sort((a, b) => a - b), [records]);

  const [geo, setGeo] = useState<GeoSelection>({ division: null, district: null, upazila: null });
  const [year, setYear] = useState<number | "all">(() => years.at(-1) ?? "all");
  const [metric, setMetric] = useState<MeasureKey>("cases");
  const [layouts, setLayouts] = useState<ResponsiveLayouts>(readStoredLayouts);
  const [expanded, setExpanded] = useState<WidgetId | null>(null);
  const modalBodyRef = useRef<HTMLDivElement>(null);
  const { width, containerRef, mounted } = useContainerWidth();

  const level: GeoLevel = geo.district ? "upazila" : geo.division ? "district" : "division";

  // Area records for the map (all children of the drilled parent) and for the analyses (incl. a chosen upazila).
  const areaRecords = useMemo(
    () => records.filter((r) => (!geo.division || r.divisionKey === geo.division.key) && (!geo.district || r.districtKey === geo.district.key)),
    [records, geo.division, geo.district],
  );
  const geoScoped = useMemo(
    () => (geo.upazila ? areaRecords.filter((r) => r.upazilaKey === geo.upazila?.key) : areaRecords),
    [areaRecords, geo.upazila],
  );
  const scoped = useMemo(() => (year === "all" ? geoScoped : geoScoped.filter((r) => r.year === year)), [geoScoped, year]);
  const mapScoped = useMemo(() => (year === "all" ? areaRecords : areaRecords.filter((r) => r.year === year)), [areaRecords, year]);
  const totals = useMemo(() => totalsOf(scoped), [scoped]);

  const areaStats = useMemo(() => {
    const stats = new Map<string, AreaStat>();
    for (const r of mapScoped) {
      const key = level === "division" ? r.divisionKey : level === "district" ? r.districtKey : r.upazilaKey;
      let s = stats.get(key);
      if (!s) {
        const label = level === "division" ? r.divisionName : level === "district" ? r.districtName : r.upazilaName;
        s = { key, label, totals: emptyTotals(), value: null };
        stats.set(key, s);
      }
      addRecord(s.totals, r);
    }
    for (const s of stats.values()) s.value = measureValue(s.totals, metric);
    return stats;
  }, [mapScoped, level, metric]);

  const breaks = useMemo(
    () =>
      metric === "cases"
        ? CASE_BREAKS[level]
        : quantileBreaks([...areaStats.values()].map((s) => s.value).filter((v): v is number => v !== null)),
    [areaStats, metric, level],
  );

  const geoOptions = useMemo<GeoOptions>(() => {
    const divisions = new Map<string, GeoPick>();
    const districts = new Map<string, Map<string, GeoPick>>();
    const upazilas = new Map<string, Map<string, GeoPick>>();
    for (const r of records) {
      if (r.divisionName === UNASSIGNED_DIVISION) continue;
      divisions.set(r.divisionKey, { key: r.divisionKey, label: r.divisionName });
      let inDivision = districts.get(r.divisionKey);
      if (!inDivision) districts.set(r.divisionKey, (inDivision = new Map()));
      inDivision.set(r.districtKey, { key: r.districtKey, label: r.districtName });
      let inDistrict = upazilas.get(r.districtKey);
      if (!inDistrict) upazilas.set(r.districtKey, (inDistrict = new Map()));
      inDistrict.set(r.upazilaKey, { key: r.upazilaKey, label: r.upazilaName });
    }
    const byLabel = (a: GeoPick, b: GeoPick) => a.label.localeCompare(b.label);
    const flatten = (m: Map<string, Map<string, GeoPick>>) => new Map([...m].map(([k, v]) => [k, [...v.values()].sort(byLabel)]));
    return { divisions: [...divisions.values()].sort(byLabel), districts: flatten(districts), upazilas: flatten(upazilas) };
  }, [records]);

  // Every analysis follows the geography, the year and the selected metric.
  const trend = useMemo(
    () =>
      [...groupTotals(scoped, (r) => r.year * 100 + r.month)]
        .sort((a, b) => a[0] - b[0])
        .map(([p, t]) => ({
          period: `${Math.floor(p / 100)}-${String(p % 100).padStart(2, "0")}`,
          value: round2(measureValue(t, metric)),
          tests: t.tests,
          tpr: round2(testPositivityRate(t.cases, t.tests)),
        })),
    [scoped, metric],
  );

  // All years → one bar per year; a single year → one bar per month of that year.
  const species = useMemo(
    () =>
      year === "all"
        ? [...groupTotals(geoScoped, (r) => r.year)]
            .sort((a, b) => a[0] - b[0])
            .map(([y, t]) => ({ label: String(y), pv: t.pv, pf: t.pf, mixed: t.mixed }))
        : [...groupTotals(scoped, (r) => r.month)]
            .sort((a, b) => a[0] - b[0])
            .map(([m, t]) => ({ label: MONTHS[m - 1].slice(0, 3), pv: t.pv, pf: t.pf, mixed: t.mixed })),
    [geoScoped, scoped, year],
  );

  // Highest to lowest (reliable rates first).
  const topAreas = useMemo(
    () =>
      [...areaStats.values()]
        .sort(
          (a, b) =>
            Number(isReliable(b, metric)) - Number(isReliable(a, metric)) ||
            (b.value ?? -Infinity) - (a.value ?? -Infinity) ||
            b.totals.cases - a.totals.cases,
        )
        .slice(0, 25),
    [areaStats, metric],
  );

  const drill = useCallback((name: string) => {
    setGeo((g) => {
      if (!g.division) return { division: { key: canonicalGeoName(name), label: name }, district: null, upazila: null };
      if (!g.district) return { ...g, district: { key: canonicalGeoName(name), label: name }, upazila: null };
      const key = upazilaMatchKey(name);
      return { ...g, upazila: g.upazila?.key === key ? null : { key, label: name } };
    });
  }, []);

  const handleLayoutChange = useCallback((_layout: unknown, all: ResponsiveLayouts) => {
    setLayouts(all);
    try {
      window.localStorage.setItem(LAYOUT_KEY, JSON.stringify(all));
    } catch {
      /* ignore */
    }
  }, []);

  const resetLayout = () => {
    setLayouts(DEFAULT_LAYOUTS);
    try {
      window.localStorage.removeItem(LAYOUT_KEY);
    } catch {
      /* ignore */
    }
  };

  const closeModal = useCallback(() => setExpanded(null), []);
  const scopeLabel = geo.upazila?.label ?? geo.district?.label ?? geo.division?.label ?? "Bangladesh";
  const forecastArea = geo.district
    ? { level: "district", key: geo.district.key, label: geo.district.label }
    : geo.division
      ? { level: "division", key: geo.division.key, label: geo.division.label }
      : { level: "national", key: "bangladesh", label: "Bangladesh" };
  const yearLabel = year === "all" ? "all loaded years" : String(year);

  const filters = (
    <>
      <GeoPicker options={geoOptions} geo={geo} onChange={setGeo} />
      <label className="flex items-center gap-1.5 text-xs text-slate-600" data-no-export="true">
        Year
        <select value={year} onChange={(e) => setYear(e.target.value === "all" ? "all" : Number(e.target.value))} className="rounded border border-slate-300 px-1.5 py-1 text-xs">
          <option value="all">All loaded</option>
          {years.map((y) => <option key={y} value={y}>{y}</option>)}
        </select>
      </label>
    </>
  );

  const widgets: Record<WidgetId, { title: string; clickToExpand: boolean; body: (big: boolean) => ReactNode }> = {
    kpis: {
      title: `Key indicators — ${scopeLabel}, ${yearLabel}`,
      clickToExpand: true,
      body: (big) => (
        <div className={`grid h-full content-start gap-2 overflow-auto ${big ? "grid-cols-2 md:grid-cols-4" : "grid-cols-2 sm:grid-cols-4 xl:grid-cols-7"}`}>
          {KPI_METRICS.map(({ key, icon }) => {
            const death = key === "deaths";
            return (
              <button
                type="button"
                key={key}
                title={`${isIndicator(key) ? `${INDICATORS[key].formula}. ` : ""}Click to show ${measureLabel(key)} on the map, trend and ranking`}
                aria-pressed={key === metric}
                onClick={(e) => {
                  e.stopPropagation();
                  setMetric(key);
                }}
                className={`flex items-center gap-3 rounded-lg border px-3 py-2 text-left transition hover:shadow ${death ? "border-red-200 bg-red-50" : isIndicator(key) ? "border-emerald-100 bg-emerald-50" : "border-slate-100 bg-slate-50"} ${key === metric ? "ring-2 ring-indigo-500" : ""}`}
              >
                <span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${death ? "bg-red-100 text-red-700" : "bg-white text-slate-600"}`}>
                  <Icon name={icon} className="h-5 w-5" />
                </span>
                <div className="min-w-0">
                  <div className={`truncate text-[11px] font-medium uppercase tracking-wide ${death ? "text-red-700" : "text-slate-500"}`}>{measureLabel(key)}</div>
                  <div className={`${big ? "text-3xl" : "text-xl"} font-bold ${death ? "text-red-700" : "text-slate-900"}`}>{formatMeasure(key, measureValue(totals, key))}</div>
                </div>
              </button>
            );
          })}
        </div>
      ),
    },
    trend: {
      title: `Monthly ${measureLabel(metric)} and ${metric === "tpr" ? "people tested" : "test positivity"} — ${scopeLabel}, ${yearLabel}`,
      clickToExpand: true,
      body: () => (
        // Two aligned panels instead of a dual-axis chart.
        <div className="flex h-full flex-col gap-1">
          <div className="min-h-0 flex-[3]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={trend} syncId="bi-trend" margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                <CartesianGrid vertical={false} stroke={GRID} />
                <XAxis dataKey="period" tick={axisTick} minTickGap={24} hide />
                <YAxis tick={axisTick} width={48} />
                <Tooltip formatter={tooltipValue} />
                <Bar dataKey="value" name={measureLabel(metric)} fill={metric === "deaths" ? DEATH_RED : SERIES[0]} radius={[2, 2, 0, 0]} isAnimationActive={false} />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <div className="min-h-0 flex-[2]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trend} syncId="bi-trend" margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                <CartesianGrid vertical={false} stroke={GRID} />
                <XAxis dataKey="period" tick={axisTick} minTickGap={24} />
                <YAxis tick={axisTick} width={48} unit={metric === "tpr" ? undefined : "%"} />
                <Tooltip formatter={tooltipValue} />
                <Line
                  dataKey={metric === "tpr" ? "tests" : "tpr"}
                  name={metric === "tpr" ? "People tested" : "Test positivity %"}
                  stroke={SERIES[1]}
                  dot={false}
                  strokeWidth={2}
                  isAnimationActive={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      ),
    },
    forecast: {
      title: `Cases, deaths & tests with 18-month forecast — ${scopeLabel}, ${yearLabel}`,
      clickToExpand: true,
      body: () => (
        <ForecastPanel area={forecastArea} records={geoScoped} year={year} latestYear={years.at(-1) ?? null} upazila={geo.upazila?.label ?? null} />
      ),
    },
    map: {
      title: `GIS — ${GEO_LEVELS[level].label} of ${geo.district?.label ?? geo.division?.label ?? "Bangladesh"}, ${yearLabel}`,
      clickToExpand: false,
      body: () => (
        <ChoroplethMap
          level={level}
          parentKey={geo.district?.key ?? geo.division?.key ?? null}
          selectedKey={geo.upazila?.key ?? null}
          stats={areaStats}
          breaks={breaks}
          metric={metric}
          onSelect={drill}
        />
      ),
    },
    species: {
      title: `Species composition of cases by ${year === "all" ? "year" : "month"} — ${scopeLabel}, ${yearLabel}`,
      clickToExpand: true,
      body: () => (
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={species} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
            <CartesianGrid vertical={false} stroke={GRID} />
            <XAxis dataKey="label" tick={axisTick} />
            <YAxis tick={axisTick} width={48} />
            <Tooltip formatter={tooltipValue} />
            <Legend wrapperStyle={{ fontSize: 12 }} />
            <Bar dataKey="pf" name="P. falciparum" stackId="s" fill={SERIES[0]} stroke={SURFACE} strokeWidth={1} isAnimationActive={false} />
            <Bar dataKey="pv" name="P. vivax" stackId="s" fill={SERIES[1]} stroke={SURFACE} strokeWidth={1} isAnimationActive={false} />
            <Bar dataKey="mixed" name="Mixed" stackId="s" fill={SERIES[2]} stroke={SURFACE} strokeWidth={1} radius={[4, 4, 0, 0]} isAnimationActive={false} />
          </BarChart>
        </ResponsiveContainer>
      ),
    },
    areas: {
      title: `${GEO_LEVELS[level].label} ranked by ${measureLabel(metric)} — ${yearLabel}`,
      clickToExpand: false,
      body: () => (
        <div className="h-full overflow-auto">
          <table className="w-full text-sm">
            <thead className="sticky top-0 bg-white text-left text-xs text-slate-500">
              <tr>
                <th className="py-1 pr-2 font-medium">Area (click to go deeper)</th>
                <th className="py-1 pr-2 text-right font-medium">Cases</th>
                <th className="py-1 pr-2 text-right font-medium text-red-700">Deaths</th>
                <th className="py-1 pr-2 text-right font-medium">TPR %</th>
                <th className="py-1 text-right font-medium">{isIndicator(metric) ? INDICATORS[metric].label : measureLabel(metric)}</th>
              </tr>
            </thead>
            <tbody>
              {topAreas.map((s) => {
                const selected = level === "upazila" && geo.upazila?.key === s.key;
                return (
                  <tr key={s.key} onClick={() => drill(s.label)} className={`cursor-pointer border-t border-slate-100 hover:bg-sky-50 ${selected ? "bg-indigo-50" : ""}`}>
                    <td className="truncate py-1 pr-2">
                      <span className="inline-block h-2.5 w-2.5 rounded-sm align-middle" style={{ background: mapColor(s.value, breaks, metric) }} />{" "}
                      {s.label}
                      {!isReliable(s, metric) && <span className="ml-1 text-[10px] text-amber-700" title={`Fewer than ${MIN_TESTS_FOR_RANKING} tests`}>low tests</span>}
                    </td>
                    <td className="py-1 pr-2 text-right tabular-nums">{formatMeasure("cases", s.totals.cases)}</td>
                    <td className={`py-1 pr-2 text-right tabular-nums ${s.totals.deaths ? "font-semibold text-red-700" : "text-slate-400"}`}>{formatMeasure("deaths", s.totals.deaths)}</td>
                    <td className="py-1 pr-2 text-right tabular-nums">{formatMeasure("tpr", measureValue(s.totals, "tpr"))}</td>
                    <td className="py-1 text-right font-semibold tabular-nums">{formatMeasure(metric, s.value)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      ),
    },
  };

  return (
    <div className="space-y-3">
      {/* One filter row scopes every analysis */}
      <div className="flex flex-wrap items-center gap-3 rounded-lg border border-slate-200 bg-white p-2 text-sm">
        <nav className="flex items-center gap-1" aria-label="Geography">
          <button type="button" onClick={() => setGeo({ division: null, district: null, upazila: null })}
            className={`rounded px-2 py-1 ${geo.division ? "text-sky-700 hover:bg-sky-50" : "font-semibold text-slate-900"}`}>
            Bangladesh
          </button>
          {geo.division && (
            <>
              <span className="text-slate-400">›</span>
              <button type="button" onClick={() => setGeo({ division: geo.division, district: null, upazila: null })}
                className={`rounded px-2 py-1 ${geo.district ? "text-sky-700 hover:bg-sky-50" : "font-semibold text-slate-900"}`}>
                {geo.division.label}
              </button>
            </>
          )}
          {geo.district && (
            <>
              <span className="text-slate-400">›</span>
              <button type="button" onClick={() => setGeo({ ...geo, upazila: null })}
                className={`rounded px-2 py-1 ${geo.upazila ? "text-sky-700 hover:bg-sky-50" : "font-semibold text-slate-900"}`}>
                {geo.district.label}
              </button>
            </>
          )}
          {geo.upazila && (
            <>
              <span className="text-slate-400">›</span>
              <span className="px-2 py-1 font-semibold text-slate-900">{geo.upazila.label}</span>
            </>
          )}
        </nav>
        {filters}
        <label className="flex items-center gap-1.5 text-xs text-slate-600">
          Map metric
          <select value={metric} onChange={(e) => setMetric(e.target.value as MeasureKey)} className="rounded border border-slate-300 px-1.5 py-1 text-xs">
            {MAP_METRICS.map((m) => <option key={m} value={m}>{measureLabel(m)}</option>)}
          </select>
        </label>
        <button type="button" onClick={resetLayout} className="ml-auto rounded border border-slate-300 px-3 py-1 text-xs hover:bg-slate-50">
          Reset layout
        </button>
      </div>

      {totals.personYears === 0 && (
        <p className="rounded border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
          No population denominators for this scope — API and ABER show “—”. Load rows into <code>upazila_population</code>.
        </p>
      )}

      <div ref={containerRef}>
        {mounted && (
          <ResponsiveGridLayout
            width={width}
            layouts={layouts}
            breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
            cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
            rowHeight={36}
            margin={[12, 12]}
            dragConfig={{ handle: ".widget-handle", cancel: ".widget-no-drag" }}
            onLayoutChange={handleLayoutChange}
          >
            {(Object.keys(widgets) as WidgetId[]).map((id) => (
              <div key={id}>
                <Widget title={widgets[id].title} downloadName={`${id}-${scopeLabel}-${yearLabel}`} onExpand={() => setExpanded(id)} clickToExpand={widgets[id].clickToExpand}>
                  {widgets[id].body(false)}
                </Widget>
              </div>
            ))}
          </ResponsiveGridLayout>
        )}
      </div>

      {expanded && (
        <Modal
          title={widgets[expanded].title}
          onClose={closeModal}
          actions={
            <>
              {filters}
              {expanded === "map" || expanded === "areas" ? (
                <label className="flex items-center gap-1.5 text-xs text-slate-600">
                  Metric
                  <select value={metric} onChange={(e) => setMetric(e.target.value as MeasureKey)} className="rounded border border-slate-300 px-1.5 py-1 text-xs">
                    {MAP_METRICS.map((m) => <option key={m} value={m}>{measureLabel(m)}</option>)}
                  </select>
                </label>
              ) : null}
              <DownloadImageButton target={modalBodyRef} filename={`${expanded}-${scopeLabel}-${yearLabel}`} />
            </>
          }
        >
          <div ref={modalBodyRef} className="h-full bg-white">{widgets[expanded].body(true)}</div>
        </Modal>
      )}
    </div>
  );
}
