"use client";

import "leaflet/dist/leaflet.css";
import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";

import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ResponsiveGridLayout, useContainerWidth, type ResponsiveLayouts } from "react-grid-layout";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { GRID, SERIES, SURFACE, axisTick, tooltipValue } from "@/lib/chart-theme";
import type { FeatureCollection } from "geojson";
import type { LatLngBounds, Map as LeafletMap, Path as LeafletPath } from "leaflet";
import {
  INDICATORS,
  addRecord,
  canonicalGeoName,
  decodeDataset,
  emptyTotals,
  formatMeasure,
  groupTotals,
  isIndicator,
  measureLabel,
  measureValue,
  totalsOf,
  UNASSIGNED_DIVISION,
  upazilaMatchKey,
  type MeasureKey,
  type MisDataset,
  type MisRecord,
  type Totals,
} from "@/lib/malaria-metrics";

/* -------------------------------- Config -------------------------------- */

type Leaflet = typeof import("leaflet");
type GeoLevel = "division" | "district" | "upazila";
type GeoRecord = MisRecord & { divisionKey: string; districtKey: string; upazilaKey: string };
interface GeoPick {
  key: string;
  label: string;
}
interface GeoSelection {
  division: GeoPick | null;
  district: GeoPick | null;
}
interface AreaStat {
  key: string;
  label: string;
  totals: Totals;
  value: number | null;
}

/**
 * Local GeoJSON in /public/geo, generated by `npm run geo:prepare`
 * (geoBoundaries BGD ADM1–3 with parent names attached).
 */
const GEO_LEVELS: Record<GeoLevel, { url: string; nameProp: string; parentProp: string | null; label: string }> = {
  division: { url: "/geo/bd-divisions.geojson", nameProp: "ADM1_EN", parentProp: null, label: "Divisions" },
  district: { url: "/geo/bd-districts.geojson", nameProp: "ADM2_EN", parentProp: "ADM1_EN", label: "Districts" },
  upazila: { url: "/geo/bd-upazilas.geojson", nameProp: "ADM3_EN", parentProp: "ADM2_EN", label: "Upazilas" },
};

const MAP_METRICS: MeasureKey[] = ["api", "tpr", "aber", "cases", "tests", "deaths"];
const KPI_METRICS: MeasureKey[] = ["cases", "tests", "tpr", "api", "aber", "deaths", "pfShare"];
// Light yellow → red; only the top class is red.
const PALETTE = ["#fef9c3", "#fde68a", "#fbbf24", "#f97316", "#dc2626"];
// Case map classes: 0 · 1–9 · 10–49 · 50–99 · ≥100 (red is reserved for 100+ cases).
const CASE_BREAKS = [0, 9, 49, 99];
const NO_DATA = "#e2e8f0";
const LAYOUT_KEY = "malaria-mis:bi-layouts:v1";

const DEFAULT_LAYOUTS: ResponsiveLayouts = {
  lg: [
    { i: "kpis", x: 0, y: 0, w: 12, h: 4, minH: 3 },
    { i: "trend", x: 0, y: 4, w: 7, h: 9, minW: 4, minH: 6 },
    { i: "map", x: 7, y: 4, w: 5, h: 14, minW: 3, minH: 8 },
    { i: "species", x: 0, y: 13, w: 7, h: 8, minW: 4, minH: 5 },
    { i: "areas", x: 7, y: 18, w: 5, h: 9, minW: 3, minH: 5 },
  ],
};

function readStoredLayouts(): ResponsiveLayouts {
  if (typeof window === "undefined") return DEFAULT_LAYOUTS;
  try {
    const parsed: unknown = JSON.parse(window.localStorage.getItem(LAYOUT_KEY) ?? "null");
    if (parsed && typeof parsed === "object" && Object.values(parsed).every(Array.isArray)) {
      return parsed as ResponsiveLayouts;
    }
  } catch {
    /* storage unavailable or corrupt */
  }
  return DEFAULT_LAYOUTS;
}

/* ------------------------------- Helpers -------------------------------- */

const round2 = (v: number | null) => (v === null ? null : Math.round(v * 100) / 100);

const LEGEND_FMT = new Intl.NumberFormat("en-US", { maximumSignificantDigits: 3 });
// Rates from fewer tests than this are ranked last in the area table (e.g. 3 tests → TPR 100%).
const MIN_TESTS_FOR_RANKING = 50;

/** Quantile upper bounds over distinct values; fewer classes when there are few areas. */
function quantileBreaks(values: number[], classes = PALETTE.length): number[] {
  const unique = [...new Set(values)].sort((a, b) => a - b);
  if (unique.length < 2) return [];
  const n = Math.min(classes, unique.length);
  const breaks: number[] = [];
  for (let i = 1; i < n; i++) breaks.push(unique[Math.floor((i * unique.length) / n) - 1]);
  return [...new Set(breaks)];
}

/** Spread the classes in use across the whole palette, light → dark. */
const paletteAt = (index: number, breakCount: number) =>
  PALETTE[breakCount ? Math.round((index * (PALETTE.length - 1)) / breakCount) : 0];

function colorFor(value: number | null, breaks: number[]): string {
  if (value === null) return NO_DATA;
  return paletteAt(breaks.filter((b) => value > b).length, breaks.length);
}

const isReliable = (s: AreaStat, metric: MeasureKey) => !isIndicator(metric) || s.totals.tests >= MIN_TESTS_FOR_RANKING;

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] ?? c);
}

const geoCache = new Map<string, Promise<FeatureCollection>>();

function loadGeoJson(url: string): Promise<FeatureCollection> {
  let pending = geoCache.get(url);
  if (!pending) {
    pending = fetch(url).then(async (res) => {
      if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
      return (await res.json()) as FeatureCollection;
    });
    pending.catch(() => geoCache.delete(url));
    geoCache.set(url, pending);
  }
  return pending;
}

/* ------------------------------ UI pieces -------------------------------- */

function Widget({ title, actions, children }: { title: string; actions?: ReactNode; children: ReactNode }) {
  return (
    <div className="flex h-full flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
      <div className="widget-handle flex cursor-move items-center justify-between gap-2 border-b border-slate-100 px-3 py-2">
        <h3 className="truncate text-sm font-semibold text-slate-700">⠿ {title}</h3>
        {actions && <div className="widget-no-drag flex cursor-default items-center gap-2">{actions}</div>}
      </div>
      <div className="min-h-0 flex-1 p-3">{children}</div>
    </div>
  );
}

function MapLegend({ breaks, metric }: { breaks: number[]; metric: MeasureKey }) {
  const counts = !isIndicator(metric) && breaks.every(Number.isInteger);
  const f = (v: number) => LEGEND_FMT.format(v);
  const items = Array.from({ length: breaks.length ? breaks.length + 1 : 0 }, (_, i) => {
    const lo = i === 0 ? null : breaks[i - 1];
    const hi = i < breaks.length ? breaks[i] : null;
    const text = counts
      ? lo === null
        ? hi === 0 ? "0" : `≤ ${f(hi ?? 0)}`
        : hi === null
          ? `≥ ${f(lo + 1)}`
          : lo + 1 === hi ? f(hi) : `${f(lo + 1)} – ${f(hi)}`
      : lo === null
        ? `≤ ${f(hi ?? 0)}`
        : hi === null
          ? `> ${f(lo)}`
          : `${f(lo)} – ${f(hi)}`;
    return { color: paletteAt(i, breaks.length), text };
  });
  return (
    <div className="pointer-events-none absolute bottom-2 left-2 z-[1000] rounded bg-white/90 p-2 text-[11px] shadow">
      <div className="mb-1 font-semibold text-slate-700">{measureLabel(metric)}</div>
      {[...items, { color: NO_DATA, text: "No data" }].map((item, i) => (
        <div key={i} className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-sm border border-slate-300" style={{ background: item.color }} />
          {item.text}
        </div>
      ))}
    </div>
  );
}

/** Explicit Division → District → Upazila drill controls (map clicks do the same). */
function GeoPicker({
  options,
  geo,
  onChange,
}: {
  options: { divisions: GeoPick[]; districts: Map<string, GeoPick[]> };
  geo: GeoSelection;
  onChange: (next: GeoSelection) => void;
}) {
  const districts = geo.division ? (options.districts.get(geo.division.key) ?? []) : [];
  const select = "max-w-32 rounded border border-slate-300 bg-white px-1 py-0.5 text-xs";
  return (
    <>
      <select
        aria-label="Division"
        value={geo.division?.key ?? ""}
        onChange={(e) => onChange({ division: options.divisions.find((d) => d.key === e.target.value) ?? null, district: null })}
        className={select}
      >
        <option value="">All divisions</option>
        {options.divisions.map((d) => (
          <option key={d.key} value={d.key}>{d.label}</option>
        ))}
      </select>
      <select
        aria-label="District"
        disabled={!geo.division}
        value={geo.district?.key ?? ""}
        onChange={(e) => onChange({ division: geo.division, district: districts.find((d) => d.key === e.target.value) ?? null })}
        className={`${select} disabled:opacity-50`}
      >
        <option value="">{geo.division ? "All districts" : "District…"}</option>
        {districts.map((d) => (
          <option key={d.key} value={d.key}>{d.label}</option>
        ))}
      </select>
      {geo.division && (
        <button
          type="button"
          onClick={() => onChange(geo.district ? { division: geo.division, district: null } : { division: null, district: null })}
          className="rounded border border-slate-300 px-1.5 py-0.5 text-xs hover:bg-slate-50"
          title="Go up one level"
        >
          ↑ Up
        </button>
      )}
    </>
  );
}

/* ----------------------------- Choropleth map ---------------------------- */

function ChoroplethMap({
  level,
  parentKey,
  stats,
  breaks,
  metric,
  onSelect,
}: {
  level: GeoLevel;
  parentKey: string | null;
  stats: Map<string, AreaStat>;
  breaks: number[];
  metric: MeasureKey;
  onSelect: (name: string) => void;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<LeafletMap | null>(null);
  const leafletRef = useRef<Leaflet | null>(null);
  const fittedRef = useRef("");
  const boundsRef = useRef<LatLngBounds | null>(null);
  const interactedRef = useRef(false);
  const onSelectRef = useRef(onSelect);
  const [ready, setReady] = useState(false);
  const [geo, setGeo] = useState<{ level: GeoLevel; data: FeatureCollection } | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    onSelectRef.current = onSelect;
  }, [onSelect]);

  // Init Leaflet client-side only.
  useEffect(() => {
    let disposed = false;
    let observer: ResizeObserver | undefined;
    let detach: (() => void) | undefined;
    import("leaflet")
      .then((mod) => {
        const el = containerRef.current;
        if (disposed || !el) return;
        const L = (mod as unknown as { default?: Leaflet }).default ?? (mod as Leaflet);
        leafletRef.current = L;
        // Wheel zoom only after a click, so page scrolling over the widget doesn't zoom the map.
        const map = L.map(el, { center: [23.7, 90.35], zoom: 7, zoomSnap: 0.25, scrollWheelZoom: false });
        L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
          maxZoom: 18,
          opacity: 0.35,
          attribution: "&copy; OpenStreetMap contributors · Boundaries: geoBoundaries",
        }).addTo(map);
        map.on("click", () => map.scrollWheelZoom.enable());
        map.on("mouseout", () => map.scrollWheelZoom.disable());
        mapRef.current = map;

        const markInteracted = () => {
          interactedRef.current = true;
        };
        el.addEventListener("pointerdown", markInteracted);
        detach = () => el.removeEventListener("pointerdown", markInteracted);

        // Grid widgets resize after mount; keep the current area framed until the user pans/zooms.
        observer = new ResizeObserver(() => {
          map.invalidateSize();
          if (boundsRef.current && !interactedRef.current) map.fitBounds(boundsRef.current, { padding: [12, 12] });
        });
        observer.observe(el);
        setReady(true);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : String(err)));
    return () => {
      disposed = true;
      detach?.();
      observer?.disconnect();
      mapRef.current?.remove();
      mapRef.current = null;
      fittedRef.current = "";
    };
  }, []);

  // Load boundaries for the current drill level.
  useEffect(() => {
    let cancelled = false;
    loadGeoJson(GEO_LEVELS[level].url)
      .then((data) => {
        if (cancelled) return;
        setGeo({ level, data });
        setError(null);
      })
      .catch((err: unknown) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      });
    return () => {
      cancelled = true;
    };
  }, [level]);

  // Draw choropleth.
  useEffect(() => {
    const map = mapRef.current;
    const L = leafletRef.current;
    if (!ready || !map || !L || !geo || geo.level !== level) return;

    const cfg = GEO_LEVELS[level];
    const nameOf = (props: Record<string, unknown> | null | undefined) => String(props?.[cfg.nameProp] ?? "");
    const keyOf = (name: string) => (level === "upazila" ? upazilaMatchKey(name) : canonicalGeoName(name));
    const features = geo.data.features.filter(
      (f) => !cfg.parentProp || !parentKey || canonicalGeoName(String(f.properties?.[cfg.parentProp] ?? "")) === parentKey,
    );

    const layer = L.geoJSON({ type: "FeatureCollection", features } as FeatureCollection, {
      style: (feature) => ({
        color: "#475569",
        weight: 0.8,
        fillOpacity: 0.85,
        fillColor: colorFor(stats.get(keyOf(nameOf(feature?.properties)))?.value ?? null, breaks),
      }),
      onEachFeature: (feature, lyr) => {
        const name = nameOf(feature.properties);
        const stat = stats.get(keyOf(name));
        lyr.bindTooltip(
          `<strong>${escapeHtml(name)}</strong><br/>` +
            `${escapeHtml(measureLabel(metric))}: ${escapeHtml(formatMeasure(metric, stat?.value ?? null))}<br/>` +
            `Cases: ${escapeHtml(formatMeasure("cases", stat?.totals.cases ?? null))} · ` +
            `Tested: ${escapeHtml(formatMeasure("tests", stat?.totals.tests ?? null))}`,
          { sticky: true },
        );
        lyr.on({
          click: () => onSelectRef.current(name),
          mouseover: (e) => (e.target as LeafletPath).setStyle({ weight: 2.5, color: "#0f172a" }),
          mouseout: (e) => layer.resetStyle(e.target as LeafletPath),
        });
      },
    }).addTo(map);

    const fitKey = `${level}|${parentKey ?? ""}`;
    if (features.length && fittedRef.current !== fitKey) {
      boundsRef.current = layer.getBounds();
      interactedRef.current = false;
      map.invalidateSize();
      map.fitBounds(boundsRef.current, { padding: [12, 12] });
      fittedRef.current = fitKey;
    }
    return () => {
      layer.remove();
    };
  }, [ready, geo, level, parentKey, stats, breaks, metric]);

  return (
    <div className="relative isolate h-full w-full overflow-hidden rounded-md">
      <div ref={containerRef} className="h-full w-full bg-slate-50" />
      <MapLegend breaks={breaks} metric={metric} />
      {error && (
        <div className="absolute inset-x-2 top-2 z-[1000] rounded bg-amber-50 p-2 text-xs text-amber-800 shadow">
          Map boundaries unavailable ({error}). Run <code>npm run geo:prepare</code>.
        </div>
      )}
    </div>
  );
}

/* ------------------------------- Component ------------------------------- */

export default function BiTab({ dataset }: { dataset: MisDataset }) {
  const records = useMemo<GeoRecord[]>(
    () =>
      decodeDataset(dataset).map((r) => ({
        ...r,
        divisionKey: canonicalGeoName(r.divisionName),
        districtKey: canonicalGeoName(r.districtName),
        upazilaKey: upazilaMatchKey(r.upazilaName),
      })),
    [dataset],
  );
  const years = useMemo(() => [...new Set(records.map((r) => r.year))].sort((a, b) => a - b), [records]);

  const [geo, setGeo] = useState<GeoSelection>({ division: null, district: null });
  const [year, setYear] = useState<number | "all">(() => years.at(-1) ?? "all");
  const [metric, setMetric] = useState<MeasureKey>("cases");
  const [layouts, setLayouts] = useState<ResponsiveLayouts>(readStoredLayouts);
  const { width, containerRef, mounted } = useContainerWidth();

  const level: GeoLevel = geo.district ? "upazila" : geo.division ? "district" : "division";

  const geoScoped = useMemo(
    () =>
      records.filter(
        (r) => (!geo.division || r.divisionKey === geo.division.key) && (!geo.district || r.districtKey === geo.district.key),
      ),
    [records, geo],
  );
  const scoped = useMemo(() => (year === "all" ? geoScoped : geoScoped.filter((r) => r.year === year)), [geoScoped, year]);
  const totals = useMemo(() => totalsOf(scoped), [scoped]);

  const areaStats = useMemo(() => {
    const stats = new Map<string, AreaStat>();
    for (const r of scoped) {
      const key = level === "division" ? r.divisionKey : level === "district" ? r.districtKey : r.upazilaKey;
      let s = stats.get(key);
      if (!s) {
        const label = level === "division" ? r.divisionName : level === "district" ? r.districtName : r.upazilaName;
        s = { key, label, totals: emptyTotals(), value: null };
        stats.set(key, s);
      }
      addRecord(s.totals, r);
    }
    for (const s of stats.values()) s.value = measureValue(s.totals, metric);
    return stats;
  }, [scoped, level, metric]);

  const breaks = useMemo(
    () =>
      metric === "cases"
        ? CASE_BREAKS
        : quantileBreaks([...areaStats.values()].map((s) => s.value).filter((v): v is number => v !== null)),
    [areaStats, metric],
  );

  const geoOptions = useMemo(() => {
    const divisions = new Map<string, GeoPick>();
    const districts = new Map<string, Map<string, GeoPick>>();
    for (const r of records) {
      if (r.divisionName === UNASSIGNED_DIVISION) continue;
      divisions.set(r.divisionKey, { key: r.divisionKey, label: r.divisionName });
      let inDivision = districts.get(r.divisionKey);
      if (!inDivision) districts.set(r.divisionKey, (inDivision = new Map()));
      inDivision.set(r.districtKey, { key: r.districtKey, label: r.districtName });
    }
    const byLabel = (a: GeoPick, b: GeoPick) => a.label.localeCompare(b.label);
    return {
      divisions: [...divisions.values()].sort(byLabel),
      districts: new Map([...districts].map(([k, m]) => [k, [...m.values()].sort(byLabel)])),
    };
  }, [records]);

  const trend = useMemo(
    () =>
      [...groupTotals(geoScoped, (r) => r.year * 100 + r.month)]
        .sort((a, b) => a[0] - b[0])
        .map(([p, t]) => ({
          period: `${Math.floor(p / 100)}-${String(p % 100).padStart(2, "0")}`,
          cases: t.cases,
          tests: t.tests,
          tpr: round2(measureValue(t, "tpr")),
        })),
    [geoScoped],
  );

  const species = useMemo(
    () =>
      [...groupTotals(geoScoped, (r) => r.year)]
        .sort((a, b) => a[0] - b[0])
        .map(([y, t]) => ({ year: String(y), pv: t.pv, pf: t.pf, mixed: t.mixed })),
    [geoScoped],
  );

  const topAreas = useMemo(
    () =>
      [...areaStats.values()]
        .sort(
          (a, b) =>
            Number(isReliable(b, metric)) - Number(isReliable(a, metric)) ||
            (b.value ?? -Infinity) - (a.value ?? -Infinity),
        )
        .slice(0, 15),
    [areaStats, metric],
  );

  const drill = useCallback((name: string) => {
    const pick = { key: canonicalGeoName(name), label: name };
    setGeo((g) => (!g.division ? { division: pick, district: null } : !g.district ? { ...g, district: pick } : g));
  }, []);

  const handleLayoutChange = useCallback((_layout: unknown, all: ResponsiveLayouts) => {
    setLayouts(all);
    try {
      window.localStorage.setItem(LAYOUT_KEY, JSON.stringify(all));
    } catch {
      /* ignore */
    }
  }, []);

  const resetLayout = () => {
    setLayouts(DEFAULT_LAYOUTS);
    try {
      window.localStorage.removeItem(LAYOUT_KEY);
    } catch {
      /* ignore */
    }
  };

  const scopeLabel = geo.district?.label ?? geo.division?.label ?? "Bangladesh";

  return (
    <div className="space-y-3">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-3 rounded-lg border border-slate-200 bg-white p-2 text-sm">
        <nav className="flex items-center gap-1" aria-label="Geography">
          <button
            type="button"
            onClick={() => setGeo({ division: null, district: null })}
            className={`rounded px-2 py-1 ${geo.division ? "text-sky-700 hover:bg-sky-50" : "font-semibold text-slate-900"}`}
          >
            Bangladesh
          </button>
          {geo.division && (
            <>
              <span className="text-slate-400">›</span>
              <button
                type="button"
                onClick={() => setGeo({ division: geo.division, district: null })}
                className={`rounded px-2 py-1 ${geo.district ? "text-sky-700 hover:bg-sky-50" : "font-semibold text-slate-900"}`}
              >
                {geo.division.label}
              </button>
            </>
          )}
          {geo.district && (
            <>
              <span className="text-slate-400">›</span>
              <span className="px-2 py-1 font-semibold text-slate-900">{geo.district.label}</span>
            </>
          )}
        </nav>

        <label className="ml-auto flex items-center gap-1.5 text-xs text-slate-600">
          Year
          <select
            value={year}
            onChange={(e) => setYear(e.target.value === "all" ? "all" : Number(e.target.value))}
            className="rounded border border-slate-300 px-2 py-1 text-sm"
          >
            <option value="all">All loaded</option>
            {years.map((y) => (
              <option key={y} value={y}>{y}</option>
            ))}
          </select>
        </label>
        <label className="flex items-center gap-1.5 text-xs text-slate-600">
          Map metric
          <select
            value={metric}
            onChange={(e) => setMetric(e.target.value as MeasureKey)}
            className="rounded border border-slate-300 px-2 py-1 text-sm"
          >
            {MAP_METRICS.map((m) => (
              <option key={m} value={m}>{measureLabel(m)}</option>
            ))}
          </select>
        </label>
        <button type="button" onClick={resetLayout} className="rounded border border-slate-300 px-3 py-1 hover:bg-slate-50">
          Reset layout
        </button>
      </div>

      {totals.personYears === 0 && (
        <p className="rounded border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
          No population denominators for this scope — API and ABER show “—”. Load rows into <code>upazila_population</code>.
        </p>
      )}

      {/* Canvas */}
      <div ref={containerRef}>
        {mounted && (
          <ResponsiveGridLayout
            width={width}
            layouts={layouts}
            breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
            cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
            rowHeight={36}
            margin={[12, 12]}
            dragConfig={{ handle: ".widget-handle", cancel: ".widget-no-drag" }}
            onLayoutChange={handleLayoutChange}
          >
            <div key="kpis">
              <Widget title={`Key indicators — ${scopeLabel}${year === "all" ? "" : `, ${year}`}`}>
                <div className="grid h-full grid-cols-2 gap-2 overflow-auto sm:grid-cols-4 xl:grid-cols-7">
                  {KPI_METRICS.map((m) => (
                    <div
                      key={m}
                      title={isIndicator(m) ? INDICATORS[m].formula : undefined}
                      className={`flex flex-col justify-center rounded-md border px-3 py-2 ${
                        isIndicator(m) ? "border-emerald-100 bg-emerald-50" : "border-slate-100 bg-slate-50"
                      }`}
                    >
                      <span className="truncate text-[11px] font-medium uppercase tracking-wide text-slate-500">{measureLabel(m)}</span>
                      <span className="text-xl font-bold tabular-nums text-slate-900">{formatMeasure(m, measureValue(totals, m))}</span>
                    </div>
                  ))}
                </div>
              </Widget>
            </div>

            <div key="trend">
              <Widget title="Monthly confirmed cases and test positivity">
                {/* Two aligned panels instead of a dual-axis chart. */}
                <div className="flex h-full flex-col gap-1">
                  <div className="min-h-0 flex-[3]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={trend} syncId="bi-trend" margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                        <CartesianGrid vertical={false} stroke={GRID} />
                        <XAxis dataKey="period" tick={axisTick} minTickGap={24} hide />
                        <YAxis tick={axisTick} width={48} />
                        <Tooltip formatter={tooltipValue} />
                        <Bar dataKey="cases" name="Confirmed cases" fill={SERIES[0]} radius={[2, 2, 0, 0]} isAnimationActive={false} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                  <div className="min-h-0 flex-[2]">
                    <ResponsiveContainer width="100%" height="100%">
                      <LineChart data={trend} syncId="bi-trend" margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                        <CartesianGrid vertical={false} stroke={GRID} />
                        <XAxis dataKey="period" tick={axisTick} minTickGap={24} />
                        <YAxis tick={axisTick} width={48} unit="%" />
                        <Tooltip formatter={tooltipValue} />
                        <Line dataKey="tpr" name="Test positivity %" stroke={SERIES[1]} dot={false} strokeWidth={2} isAnimationActive={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </Widget>
            </div>

            <div key="map">
              <Widget
                title={`GIS — ${GEO_LEVELS[level].label} of ${scopeLabel}`}
                actions={<GeoPicker options={geoOptions} geo={geo} onChange={setGeo} />}
              >
                <ChoroplethMap
                  level={level}
                  parentKey={geo.district?.key ?? geo.division?.key ?? null}
                  stats={areaStats}
                  breaks={breaks}
                  metric={metric}
                  onSelect={drill}
                />
              </Widget>
            </div>

            <div key="species">
              <Widget title="Species composition by year">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={species} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                    <CartesianGrid vertical={false} stroke={GRID} />
                    <XAxis dataKey="year" tick={axisTick} />
                    <YAxis tick={axisTick} width={48} />
                    <Tooltip formatter={tooltipValue} />
                    <Legend wrapperStyle={{ fontSize: 12 }} />
                    <Bar dataKey="pf" name="P. falciparum" stackId="s" fill={SERIES[0]} stroke={SURFACE} strokeWidth={1} isAnimationActive={false} />
                    <Bar dataKey="pv" name="P. vivax" stackId="s" fill={SERIES[1]} stroke={SURFACE} strokeWidth={1} isAnimationActive={false} />
                    <Bar dataKey="mixed" name="Mixed" stackId="s" fill={SERIES[2]} stroke={SURFACE} strokeWidth={1} radius={[4, 4, 0, 0]} isAnimationActive={false} />
                  </BarChart>
                </ResponsiveContainer>
              </Widget>
            </div>

            <div key="areas">
              <Widget title={`Top ${GEO_LEVELS[level].label.toLowerCase()} by ${measureLabel(metric)}`}>
                <div className="h-full overflow-auto">
                  <table className="w-full text-sm">
                    <thead className="sticky top-0 bg-white text-left text-xs text-slate-500">
                      <tr>
                        <th className="py-1 pr-2 font-medium">Area</th>
                        <th className="py-1 pr-2 text-right font-medium">Cases</th>
                        <th className="py-1 pr-2 text-right font-medium">TPR %</th>
                        <th className="py-1 text-right font-medium">{isIndicator(metric) ? INDICATORS[metric].label : measureLabel(metric)}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {topAreas.map((s) => (
                        <tr
                          key={s.key}
                          onClick={level === "upazila" ? undefined : () => drill(s.label)}
                          className={`border-t border-slate-100 ${level === "upazila" ? "" : "cursor-pointer hover:bg-sky-50"}`}
                        >
                          <td className="truncate py-1 pr-2">
                            {s.label}
                            {!isReliable(s, metric) && (
                              <span className="ml-1 text-[10px] text-amber-700" title={`Fewer than ${MIN_TESTS_FOR_RANKING} tests`}>
                                low tests
                              </span>
                            )}
                          </td>
                          <td className="py-1 pr-2 text-right tabular-nums">{formatMeasure("cases", s.totals.cases)}</td>
                          <td className="py-1 pr-2 text-right tabular-nums">{formatMeasure("tpr", measureValue(s.totals, "tpr"))}</td>
                          <td className="py-1 text-right font-semibold tabular-nums">{formatMeasure(metric, s.value)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </Widget>
            </div>
          </ResponsiveGridLayout>
        )}
      </div>
    </div>
  );
}
